name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run smoke tests
        run: npm run test:smoke

      - name: Run unit tests with coverage
        run: npm run test:unit:focused:coverage:ci
        env:
          JEST_JUNIT_OUTPUT_DIR: coverage
          JEST_JUNIT_OUTPUT_NAME: junit-focused.xml

      - name: Run integration tests
        run: npm run test:integration

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-coverage
          path: |
            backend/coverage/**
            backend/coverage-current/**

      - name: Upload JUnit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-junit
          path: backend/coverage/junit-focused.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: backend/coverage
          flags: backend
          name: zinnol-backend
          fail_ci_if_error: false